// <auto-generated />
using System;
using InteractiveData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InteractiveData.Migrations
{
    [DbContext(typeof(AmpContext))]
    [Migration("20190717105549_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InteractiveUserGuide.Amplifier", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("InteractiveAmplifiers");
                });

            modelBuilder.Entity("InteractiveUserGuide.Element", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AmplifierID");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("AmplifierID");

                    b.ToTable("InteractiveElements");
                });

            modelBuilder.Entity("InteractiveUserGuide.Element", b =>
                {
                    b.HasOne("InteractiveUserGuide.Amplifier", "Amplifier")
                        .WithMany("Elements")
                        .HasForeignKey("AmplifierID");
                });
#pragma warning restore 612, 618
        }
    }
}
