// <auto-generated />
using InteractiveData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InteractiveData.Migrations
{
    [DbContext(typeof(AmpContext))]
    partial class AmpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InteractiveDomain.AmplifierModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Model");

                    b.Property<int>("Power");

                    b.HasKey("Id");

                    b.ToTable("InteractiveAmplifiers");
                });

            modelBuilder.Entity("InteractiveDomain.ElementModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AmplifierModelId");

                    b.Property<string>("Description");

                    b.Property<string>("MeshName");

                    b.Property<string>("Name");

                    b.Property<string>("Panel");

                    b.HasKey("Id");

                    b.HasIndex("AmplifierModelId");

                    b.ToTable("InteractiveElements");
                });

            modelBuilder.Entity("InteractiveDomain.ElementModel", b =>
                {
                    b.HasOne("InteractiveDomain.AmplifierModel", "Amplifier")
                        .WithMany("Elements")
                        .HasForeignKey("AmplifierModelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
